#include "LPC11Uxx.h"
#include "bit.h"
#include "../variables.h"
#include <stdint.h>


void timerInit(void){

	if ( ~(LPC_SYSCON->SYSAHBCLKCTRL & 0x80) ){
		LPC_SYSCON->SYSAHBCLKCTRL |= (1 << 7); // ATIVA O CLOCK DO BARRAMENTO AHB DO BLOCO DE COUNTER/TIMER 0 DE 16 BITS
	}

	LPC_SYSCON->SYSAHBCLKCTRL |= (1 << 8); // ATIVA O CLOCK DO BARRAMENTO AHB DO BLOCO DE COUNTER/TIMER 1 DE 16 BITS


	BitClr(LPC_CT16B0->CTCR, 0); //COLOCA O REGISTRADOR CT16B0 COMO TIMER
	BitClr(LPC_CT16B1->CTCR, 0); //COLOCA O REGISTRADOR CT16B1 COMO TIMER

	BitClr(LPC_CT16B0->TCR, 0); // DESABILITA A CONTAGEM DO TIMER
	BitSet(LPC_CT16B0->TCR, 1);  // RENICIA O TIMER COUNTER E O PRESCALER DE FORMA SINCRONIZADA NA PRÓXIMA BORDA POSITIVA DO PCLK
	BitClr(LPC_CT16B0->TCR, 1); // FINALIZA A RENICIALIZAÇÃO

	BitClr(LPC_CT16B1->TCR, 0); // DESABILITA A CONTAGEM DO TIMER
	BitSet(LPC_CT16B1->TCR, 1);  // RENICIA O TIMER COUNTER E O PRESCALER DE FORMA SINCRONIZADA NA PRÓXIMA BORDA POSITIVA DO PCLK
	BitClr(LPC_CT16B1->TCR, 1); // FINALIZA A RENICIALIZAÇÃO

	LPC_CT16B0->PR = 0x000B; // ESPECIFICA O VALOR MÁXIMO DO PRESCALER PARA 12
	LPC_CT16B1->PR = 0x000B; // ESPECIFICA O VALOR MÁXIMO DO PRESCALER PARA 12

	LPC_CT16B1->MR[0] = 1000; //VALOR DO REGISTRADOR 0 DE MATCH = 1000 = 1mS, PARA UM PRESCALER DE 12 E FREQUENCIA DE 12MHZ
	BitSet(LPC_CT16B1->MCR, 2); //ATIVA O STOP DO TIMER CONTROL E DO PRESCALER QUANDO O MATCH BATER COM O TIMER CONTROL


}

void timerCounter(void){
	if(LPC_CT16B1->MR[0] <= 1000){

		BitSet(LPC_CT16B1->TCR, 0); // HABILITA A CONTAGEM
	}

	if (LPC_CT16B1->TC == 1000){
		BitSet(LPC_CT16B1->TCR, 1);
		BitClr(LPC_CT16B1->TCR, 1); // FINALIZA A RENICIALIZAÇÃO
		addMilSeg();
		BitSet(LPC_CT16B1->TCR, 0); // HABILITA A CONTAGEM
	}
	if (getMilSeg() == 50){
		addSeg();
		resetMilSeg();
	}
	if (getSeg() == 60){
		addMin();
		resetSeg();
	}
	if (getMin() == 60){
		addHr();
		resetMin();
	}
	if (getHr() == 100){
		resetMilSeg();
		resetSeg();
		resetMin();
		resetHr();
	}
}



void timerStart(uint32_t time){

	LPC_CT16B0->MR[0] = 1000; //VALOR DO REGISTRADOR 0 DE MATCH = 1000 = 1mS, PARA UM PRESCALER DE 12 E FREQUENCIA DE 12MHZ
	BitSet(LPC_CT16B0->MCR, 2); //ATIVA O STOP DO TIMER CONTROL E DO PRESCALER QUANDO O MATCH BATER COM O TIMER CONTROL
	BitSet(LPC_CT16B0->TCR, 0); // HABILITA A CONTAGEM

}

void timerWait(void){

	while(LPC_CT16B0->TC != LPC_CT16B0->MR[0]);

	BitClr(LPC_CT16B0->TCR, 0); // DESABILITA A CONTAGEM
	BitSet(LPC_CT16B0->TCR, 1);  // RENICIA O TIMER COUNTER E O PRESCALER COUNTER DE FORMA SINCRONIZADA NA PRÓXIMA BORDA POSITIVA DO PCLK
	BitClr(LPC_CT16B0->TCR, 1);
}

void delay(uint32_t time){
	uint32_t ms = 0;

	LPC_CT16B0->MR[0] = 1000; //VALOR DO REGISTRADOR 0 DE MATCH = 1000 = 1mS, PARA UM PRESCALER DE 12 E FREQUENCIA DE 12MHZ
	BitSet(LPC_CT16B0->MCR, 2); //ATIVA O STOP DO TIMER CONTROL E DO PRESCALER QUANDO O MATCH BATER COM O TIMER CONTROL
	BitSet(LPC_CT16B0->TCR, 0); // HABILITA A CONTAGEM


	while(ms != time){


		if (LPC_CT16B0->TC == 1000){

			BitSet(LPC_CT16B0->TCR, 1);  // RENICIA O TIMER COUNTER E O PRESCALER COUNTER DE FORMA SINCRONIZADA NA PRÓXIMA BORDA POSITIVA DO PCLK
			ms++;
			BitClr(LPC_CT16B0->TCR, 1); // FINALIZA A RENICIALIZAÇÃO
			BitSet(LPC_CT16B0->TCR, 0); // HABILITA A CONTAGEM

		}

	}

	BitClr(LPC_CT16B0->TCR, 0); // DESABILITA A CONTAGEM
	BitSet(LPC_CT16B0->TCR, 1);
	BitClr(LPC_CT16B0->TCR, 1);
}


void delay_us(uint32_t time){

	LPC_CT16B0->MR[0] = time;
	BitSet(LPC_CT16B0->MCR, 2);
	BitSet(LPC_CT16B0->TCR, 0);

	while (LPC_CT16B0->TC != time);

	BitClr(LPC_CT16B0->TCR, 0);
	BitSet(LPC_CT16B0->TCR, 1);
	BitClr(LPC_CT16B0->TCR, 1);



}
